# -*- coding: utf-8 -*-

antigate_key='ea0d80c9fb33dabcc96ffae566fe7b45'

useragent= "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:21.0) Gecko/20100101 Firefox/21.0"
useragent= "Mozilla/5.0 (SymbianOS/9.2 U; Series60/3.1 NokiaN95/"
useragent= "Opera/12.15 (S60; SymbOS; Opera Mobi/447; U; ru) Presto/2.4.18 Version/10.00"

image_path='/home/vovan/PhotoS/'
len_pass=20

xml_db_path='/home/vovan/eclipse/PaseBook/'
date_format="%d-%m-%Y %H:%M:%S"
street_arr=[
'Советская ул',
'Молодежная ул',
'Центральная ул',
'Школьная ул',
'Новая ул',
'Садовая ул',
'Лесная ул',
'Ленина ул',
'Мира ул',
'Октябрьская ул',
'Зеленая ул',
'Комсомольская ул',
'Заречная ул',
'Первомайская ул',
'Гагарина ул',
'Полевая ул',
'Луговая ул',
'Пионерская ул',
'Кирова ул',
'Юбилейная ул',
'Северная ул',
'Пролетарская ул',
'Степная ул',
'Пушкина ул',
'Калинина ул',
'Южная ул',
'Колхозная ул',
'Рабочая ул',
'Солнечная ул',
'Железнодорожная ул',
'Восточная ул',
'Заводская ул',
'Чапаева ул',
'Нагорная ул',
'Строителей ул',
'Береговая ул',
'Победы ул',
'Горького ул',
'Кооперативная ул',
'Красноармейская ул',
'Совхозная ул',
'Речная ул',
'Школьный пер',
'Спортивная ул',
'Озерная ул',
'Строительная ул',
'Парковая ул',
'Чкалова',
'Мичурина',
		]
		
residence_arr=[
			
    'Москва', 
    'Санкт-Петербург',
    'Новосибирск', 
    'Нижний Новгород', 
    'Екатеринбург',
    'Самара',
    'Омск', 
    'Челябинск',
    'Ростов-на-Дону',
    'Волгоград',

			]
rus_fam=['Смирнов',
'Иванов',
'Кузнецов',
'Попов',
'Соколов',
'Лебедев',
'Козлов',
'Новиков',
'Морозов',
'Петров',
'Волков',
'Соловьев',
'Васильев',
'Зайцев',
'Павлов',
'Семенов',
'Голубев',
'Виноградов',
'Богданов',
'Воробьев',
'Федоров',
'Михайлов',
'Беляев',
'Тарасов',
'Белов',
'Комаров',
'Орлов',
'Киселев',
'Макаров',
'Андреев',
'Ковалев',
'Ильин',
'Гусев',
'Титов',
'Кузьмин',
'Кудрявцев',
'Баранов',
'Куликов',
'Алексеев',
'Степанов',
'Яковлев',
'Сорокин',
'Сергеев',
'Романов',
'Захаров',
'Борисов',
'Королев',
'Герасимов',
'Пономарев',
'Григорьев',
'Лазарев',
'Медведев',
'Ершов',
'Никитин',
'Соболев',
'Рябов',
'Поляков',
'Цветков',
'Данилов',
'Жуков',
'Фролов',
'Журавлев',
'Николаев',
'Крылов',
'Максимов',
'Сидоров',
'Осипов',
'Белоусов',
'Федотов',
'Дорофеев',
'Егоров',
'Матвеев',
'Бобров',
'Дмитриев',
'Калинин',
'Анисимов',
'Петухов',
'Антонов',
'Тимофеев',
'Никифоров',
'Веселов',
'Филиппов',
'Марков',
'Большаков',
'Суханов',
'Миронов',
'Ширяев',
'Александров',
'Коновалов',
'Шестаков',
'Казаков',
'Ефимов', 
'Денисов', 
'Громов', 
'Фомин', 
'Давыдов', 
'Мельников',
'Щербаков', 
'Блинов', 
'Колесников',
'Карпов', 
'Афанасьев',
'Власов',
'Маслов', 
'Исаков', 
'Тихонов', 
'Аксенов', 
'Гаврилов', 
'Родионов', 
'Котов', 
'Горбунов',
'Кудряшов',
'Быков', 
'Зуев', 
'Третьяков', 
'Савельев', 
'Панов', 
'Рыбаков', 
'Суворов', 
'Абрамов', 
'Воронов', 
'Мухин',
'Архипов', 
'Трофимов',
'Мартынов', 
'Емельянов',
'Горшков', 
'Чернов',
'Овчинников', 
'Селезнев', 
'Панфилов', 
'Копылов', 
'Михеев', 
'Галкин', 
'Назаров', 
'Лобанов', 
'Лукин', 
'Беляков', 
'Потапов', 
'Некрасов', 
'Хохлов', 
'Жданов', 
'Наумов', 
'Шилов', 
'Воронцов', 
'Ермаков', 
'Дроздов', 
'Игнатьев', 
'Савин', 
'Логинов',
'Сафонов', 
'Капустин', 
'Кириллов', 
'Моисеев', 
'Елисеев', 
'Кошелев', 
'Костин', 
'Горбачев', 
'Орехов', 
'Ефремов', 
'Исаев', 
'Евдокимов', 
'Калашников', 
'Кабанов', 
'Носков', 
'Юдин', 
'Кулагин', 
'Лапин', 
'Прохоров', 
'Нестеров', 
'Харитонов', 
'Агафонов', 
'Муравьев',
'Ларионов', 
'Федосеев', 
'Зимин', 
'Пахомов', 
'Шубин', 
'Игнатов', 
'Филатов', 
'Крюков', 
'Рогов', 
'Кулаков', 
'Терентьев', 
'Молчанов', 
'Владимиров',
'Артемьев', 
'Гурьев', 
'Зиновьев', 
'Гришин', 
'Кононов', 
'Дементьев', 
'Ситников', 
'Симонов', 
'Мишин', 
'Фадеев', 
'Комиссаров', 
'Мамонтов', 
'Носов', 
'Гуляев', 
'Шаров', 
'Устинов', 
'Вишняков', 
'Евсеев', 
'Лаврентьев', 
'Брагин', 
'Константинов', 
'Корнилов', 
'Авдеев', 
'Зыков', 
'Бирюков', 
'Шарапов', 
'Никонов', 
'Щукин', 
'Дьячков', 
'Одинцов', 
'Сазонов', 
'Якушев', 
'Красильников',
'Гордеев', 
'Самойлов', 
'Князев', 
'Беспалов', 
'Уваров', 
'Шашков', 
'Бобылев', 
'Доронин', 
'Белозеров', 
'Рожков', 
'Самсонов', 
'Мясников', 
'Лихачев', 
'Буров', 
'Сысоев', 
'Фомичев', 
'Русаков', 
'Стрелков', 
'Гущин', 
'Тетерин', 
'Колобов', 
'Субботин', 
'Фокин', 
'Блохин', 
'Селиверстов',
'Пестов', 
'Кондратьев',
'Силин', 
'Меркушев',
'Лыткин', 
'Туров',]

male_firstname=[
#Copy 1
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',
#Copy 2
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',
#Copy 3
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',
#Copy 4
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',
#Copy 5
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',
#Copy 6
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',
#Copy 7
'Александр',
'Алексей',
'Анатолий',
'Андрей',
'Антон',
'Борис',
'Вадим',
'Валентин',
'Валерий',
'Василий',
'Виктор',
'Виталий',
'Владимир',
'Геннадий',
'Георгий',
'Денис',
'Дмитрий',
'Евгений',
'Егор',
'Иван',
'Игорь',
'Илья',
'Константин',
'Леонид',
'Михаил',
'Никита',
'Николай',
'Олег',
'Павел',
'Пётр',
'Роман',
'Семён',
'Сергей',
'Фёдор',
'Юрий',
'Ярослав',
'Максим',
'Леонид',
'Степан',
'Кирилл',
'Георгий',

'Аркадий',
'Артём',
'Артемий',
'Афанасий',
'Богдан',
'Владислав',
'Всеволод',
'Вячеслав',
'Гаврила',
'Герасим',
'Герман',
'Глеб',
'Григорий',
'Давыд',
'Данила',
'Даниил',
'Елисей',
'Ефрем',
'Захар',
'Иосиф',
'Ипполит',
'Кир',
'Кондрат',
'Конон',
'Корней',
'Кузьма',
'Лавр',
'Лаврентий',
'Лев',
'Леон',
'Леонтий',
'Макар',
'Мариан',
'Марк',
'Матвей',
'Мирон',
'Мирослав',
'Остап',
'Панкрат',
'Парамон',
'Платон',
'Потап',
'Прокофий',
'Прохор',
'Радислав',
'Ратмир',
'Родион',
'Ростислав',
'Руслан',
'Савелий',
'Святослав',
'Севастьян',
'Серафим',
'Сильвестр',
'Спартак',
'Станислав',
'Тарас',
'Терентий',
'Тимофей',
'Тимур',
'Тит',
'Тихон',
'Трофим',
'Ульян',
'Федот',
'Феликс',
'Филимон',
'Филипп',
'Филип',
'Фома',
'Харитон',
'Христофор',
'Эдуард',
'Эммануил',
'Эрнест',
'Юлий',
'Яков',
'Ян',
]

female_firstname=['Александра',
#copy 1
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',
#copy 1
'Александра',
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',
#copy 1
'Александра',
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',
#copy 1
'Александра',
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',
#copy 1
'Александра',
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',
#copy 1
'Александра',
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',
#copy 1
'Александра',
'Алла',
'Анастасия',
'Анна',
'Валетина',
'Валерия',
'Вера',
'Вероника',
'Виктория',
'Галина',
'Дарья',
'Евгения',
'Екатерина',
'Катерина',
'Елена',
'Зоя',
'Инна',
'Ирина',
'Катерина',
'Екатерина',
'Ксения',
'Лариса',
'Людмила',
'Марина',
'Мария',
'Надежда',
'Наталья',
'Ольга',
'Светлана',
'Тамара',
'Татьяна',
'Юлия',
'Любовь',
'Надежда',
'Оксана',

'Августа',
'Агата',
'Алевтина',
'Алина',
'Алиса',
'Альбина',
'Настасья',
'Антонина',
'Анфиса',
'Ванда',
'Варвара',
'Василиса',
'Виргиния',
'Диана',
'Дина',
'Ева',
'Елизавета',
'Жанна',
'Зинаида',
'Клара',
'Лада',
'Лидия',
'Лилия',
'Луиза',
'Майя',
'Маргарита',
'Мальвина',
'Настасья',
'Анастасия',
'Наталия',
'Ника',
'Полина',
'Раиса',
'Регина',
'Рената',
'Римма',
'Роза',
'Сильвия',
'Софья',
'Стелла',
'Таисия',
'Ульяна',
'Фаина',
'Эвелина',
'Элеонора',
'Эльвира',
'Эмма',
]
university_arr=[
'Московский государственный технический университет им. H.Э.Баумана ',
'Академический международный институт ',
'Академия Гуманитарного Образования ',
'Академия труда и социальных отношений Федерации Независимых Профсоюзов России ',
'Балтийская академия туризма и предпринимательства ',
'Балтийский институт иностранных языков и международного сотрудничества ',
'Балтийский Институт Экологии, Политики и Права ',
'Военно-транспортный университет Железнодорожных войск ',
'Всероссийская академия внешней торговли Министерства экономического развития РФ ',
'Всероссийская государственная налоговая академия Министерства финансов РФ ',
'Всероссийский заочный финансово-экономический институт ',
'Государственный университет Министерства финансов Российской Федерации ',
'Государственный университет по землеустройству ',
'Государственный университет управления ',
'Дипломатическая академия Министерства иностранных дел Российской Федерации ',
'Институт международного права и экономики им.А.С.Грибоедова ',
'Институт экономики и финансов ',
'Международный банковский институт ',
'Международный институт экономики и права ',
'Международный университет в Москве ',
'Межотраслевой технологический институт ',
'Московская государственная академия водного транспорта ',
'Московская Государственная Академия Коммунального Хозяйства и Строительства ',
'Московская государственная академия тонкой химической технологии им. М.В. Ломоносова ',
'Московская финансово-юридическая академия ',
'Московский авиационный институт',
'Московский архитектурный институт',
'Московский городской педагогический университет ',
'Московский государственный автомобильно-дорожный университет',
'Московский государственный агроинженерный университет им. В.П. Горячкина ',
'Московский государственный горный университет ',
'Московский государственный гуманитарный университет имени М.А.Шолохова ',
'Московский государственный индустриальный университет ',
'Московский государственный институт радиотехники, электроники и автоматики',
'Московский государственный институт электроники и математики',
'Московский государственный институт электронной техники',
'Московский государственный лингвистический университет ',
'Московский государственный областной университет ',
'Московский государственный открытый университет ',
'Московский государственный строительный университет ',
'Московский государственный текстильный университет им. А.Н. Косыгина ',
'Московский государственный технический университет "МАМИ" ',
'Московский государственный технический университет гражданской авиации ',
'Московский государственный технологический университет "Станкин" ',
'Московский государственный университет геодезии и картографии ',
'Московский государственный университет им. М.В. Ломоносова ',
'Московский государственный университет международных отношений МИД России',
'Московский государственный университет печати ',
'Московский государственный университет пищевых производств ',
'Московский Государственный университет приборостроения и информатики ',
'Московский государственный университет прикладной биотехнологии ',
'Московский государственный университет природообустройства ',
'Московский государственный университет путей сообщения ',
'Московский государственный университет экономики, статистики и информатики',
'Московский гуманитарный институт им. Е.Р. Дашковой ',
'Московский гуманитарный университет ',
'Московский педагогический государственный университет ',
'Московский технический университет связи и информатики ',
'Московский технологический институт "ВТУ" ',
'Московский Университет имени С.Ю.Витте',
'Московский финансово-промышленный университет Синергия ',
'Московский энергетический институт',
'Национальный исследовательский университет «Высшая школа экономики» ',
'Национальный открытый институт России ',
'Невский институт языка и культуры ',
'Невский университет ',
'Петербургский государственный университет путей сообщения ',
'Российская академия государственной службы при Президенте РФ ',
'Российская академия народного хозяйства и государственной службы при Президенте Российской Федерации ',
'Российский государственный аграрный университет МСХА им.Тимирязева ',
'Российский государственный геологоразведочный университет ',
'Российский государственный гидрометеорологический университет ',
'Российский государственный гуманитарный университет ',
'Российский государственный педагогический университет имени А.И.Герцена ',
'Российский государственный социальный университет ',
'Российский государственный технологический университет им. К.Э. Циолковского',
'Российский государственный торгово-экономический университет ',
'Российский государственный университет инновационных технологий и предпринимательства ',
'Российский государственный университет нефти и газа им. И.М. Губкина ',
'Российский государственный университет туризма и сервиса ',
'Российский университет дружбы народов ',
'Российский химико-технологический университет им. Д.И. Менделеева ',
'Российский экономический университет им. Г.В. Плеханова ',
'Ростовский филиал Российского государственного гидрометеорологического университета ',
'Санкт-Петербургская академия управления и экономики ',
'Санкт-Петербургский академический университет РАН ',
'Санкт-Петербургский государственный архитектурно-строительный университет ',
'Санкт-Петербургский государственный горный институт им. Г.В.Плеханова',
'Санкт-Петербургский государственный инженерно-экономический университет ',
'Санкт-Петербургский государственный институт машиностроения ',
'Санкт-Петербургский государственный морской технический университет ',
'Санкт-Петербургский государственный политехнический университет ',
'Санкт-Петербургский государственный технологический институт',
'Санкт-Петербургский государственный технологический университет растительных полимеров ',
'Санкт-Петербургский государственный университет ',
'Санкт-Петербургский государственный университет аэрокосмического приборостроения ',
'Санкт-Петербургский государственный университет водных коммуникаций ',
'Санкт-Петербургский государственный университет гражданской авиации ',
'Санкт-Петербургский государственный университет информационных технологий, механики и оптики ',
'Санкт-Петербургский государственный университет низкотемпературных и пищевых технологий ',
'Санкт-Петербургский государственный университет сервиса и экономики ',
'Санкт-Петербургский государственный университет телекоммуникаций им. проф. М.А. Бонч-Бруевича ',
'Санкт-Петербургский государственный университет технологии и дизайна ',
'Санкт-Петербургский государственный университет экономики и финансов ',
'Санкт-Петербургский государственный электротехнический университет "ЛЭТИ" ',
'Санкт-Петербургский гуманитарный университет профсоюзов ',
'Санкт-Петербургский им. В.Б. Бобкова филиал Российской таможенной академии ',
'Санкт-Петербургский институт внешнеэкономических связей, экономики и права ',
'Санкт-Петербургский институт Московского государственного университета печати ',
'Санкт-Петербургский институт права имени Принца П. Г. Ольденбургского ',
'Санкт-Петербургский международный институт менеджмента ',
'Санкт-Петербургский социально-экономический институт ',
'Санкт-Петербургский торгово-экономический институт ',
'Санкт-Петербургский филиал Государственного университета - Высшей школы экономики ',
'Северо-западная академия государственной службы ',
'Северо-Западный государственный заочный технический университет ',
'Смольный институт Российской академии образования ',
'Современная гуманитарная академия ',
'Финансовый университет при Правительстве РФ ',

			]
university_arr_old=[
'Academic Law University',
'Adygei State University',
'Altai State Technical University',
'Altai State University',
'Altay State Agrarian University',
'Altay State Medical University',
'Amur State University (AmSU)',
'Arkhangelsk State Technical University',
'Astrakhan State Technical University',
'Astrakhan State University',
'Azov State University of Technology',
'Baikal National University of Economics and Law, Irkutsk',
'Baikal State University of Economy and Right',
'Baltic State Technical University',
'Baltic University of Ecology, Politics and Law (BUEPL)',
'Barnaul State Pedagogical University',
'Bashkir State Agrarian University',
'Bashkir State Medical University',
'Bashkir State Pedagogical University the Name of M.Akmully',
'Bashkir State University',
'Bauman Moscow State Technical University',
'Baykal State University of Economics and Law (Filial)',
'Belgorod Shukhov State Technological University',
'Belgorod State Technological University named after V.G. Shukhov',
'Belgorod State University',
'Belgorod University of Cooperation, Economics and Law',
'Biysk State Padagogical University',
'Biysk State Padagogical University after V.M. Shukshin',
'Blagoveshchensk State Pedagogical University',
'Bratsk State Technical University',
'Bratsky State University',
'Bryansk State Technical University',
'Bugulminsky Banch of the Kazan State Technical University of A.N.Tupolev',
'Buryat State University',
'Chechen State University',
'Cheljabinsk State University',
'Chelyabinsk State Agroengineering University',
'Chelyabinsk State Pedagogical University',
'Chelyabinsk State Technical University',
'Chelyabinsk State University',
'Chelyabinsk State University Agrotechnical',
'Cherepovets State University',
'Chita State Technical University',
'Chuvash State Pedagogical University',
'Dagestan State Pedagogical University',
'Dagestan State University',
'Daghestan State Pedagogical University',
'Daghestan State Technical University',
'Don State Agrarian University',
'Don State Technical University',
'East Siberian State University of Technology',
'East University',
'Elabuga State Pedagogical University',
'Elabuzhskiy State Pedagogical University',
'European University of Right JUSTO',
'European University Saint Petersburg',
'Far East State Agrarian University',
'Far East State Medical University',
'Far East State Technical University',
'Far East State Transport University',
'Far Eastern Federal University',
'Far Eastern National University',
'Far Eastern State University of the Humanities',
'Filiale Beresnuki von der Staatsuniversität Perm',
'Financial University under the Government of the Russian Federation',
'Gorno Altaisk State University',
'Gorsky (Mountain) State Agrarian University',
'Graduate School of Corporate Management',
'Gubkin Russian State University of Oil and Gas',
'Herzen State Pedagogical University of Russia',
'Humanitär-Pädagogische Staatsuniversität von Amur',
'Humanitarian University',
'I.G.Petrovsky Bryansk State University',
'Immanuel Kant State University of Russia (Kaliningrad State University)',
'Ingush State University',
'International East-European University',
'International Independent University of Environmental and Political Sciences',
'International University Moscow',
'International University of Engineering Moscow',
'International University of Fundamental Studies Saint Petersburg',
'International University Saint Petersburg',
'Irkuck State University of Medicine',
'Irkutsk State Linguistic University',
'Irkutsk State Medical University',
'Irkutsk State Pedagogical University',
'Irkutsk State Railway Transport Engineering University',
'Irkutsk State Technical University',
'Irkutsk State University',
'Ivanovo State Power University',
'Ivanovo State University',
'Izhevsk State Technical University',
'Izhevsk State Technical University Russia',
'Jaroslavl State University',
'Jewish University Moscow',
'Kabardino Balkarian State University',
'Kaliningrad State Technical University',
'Kalmyk State University',
'Kaluga State Pedagogical University',
'Kaluga State Teachers University',
'Kamchatka State Technical University',
'Karachay-Cherkessia State University',
'Karelian State Pedagogical University',
'Kazan (Volga) Federal University',
'Kazan Federal University',
'Kazan State Agrarian University',
'Kazan State Medical University',
'Kazan State Pedagogical University',
'Kazan State Power Engineering University',
'Kazan State Technological University',
'Kazan State University',
'Kazan State University of Architecture and Engineering',
'Kazan State University of Culture and Arts',
'Kazan State University of Technology',
'Kemerovo State University',
'Kemerovo State University of Culture and Arts',
'Khakassian State University Named After N.F. Katanova',
'Kiev National Medical University',
'Komsomolsk On Amur State Technical University',
'Kostroma State Technological University',
'Kostroma State University named after NA Nekrasov',
'Krasnodar State Medical University',
'Krasnodarsky University of Ministry of Internal Affairs of Russian Federation',
'Krasnoyarsk State Medical University named after Professor V.F.Voyno-Jasenzezkogo',
'Krasnoyarsk State Pedagogical University',
'Krasnoyarsk State Technical University',
'Krasnoyarsk State University',
'Krasnoyarsk State University of Agriculture',
'Kuban State Agrarian University',
'Kuban State Medical University',
'Kuban State Technological University',
'Kuban State University',
'Kuban State University of Physical Education Sport and Tourism',
'Kuban State University of Technology',
'Kurgan International University',
'Kurgan State University',
'Kursk State Medical University Federal Agency for Health and Social Development',
'Kursk State Technical University',
'Kursk State University',
'Kursk State University, Kursk',
'Kuzbass State Technical University',
'Kyban State Agrarian University',
'Leningrad State University',
'Leningrad State University A. S. Pushkin',
'Lev Tolstoi State Pedagogical University',
'Lipetsk State Pedagogical University',
'Lipetsk State Technical University',
'Lipetsky State Pedagogical University',
'Lomonosov Moscow State University',
'Magnitogorsk State Technical University',
'Magnitogorsk State University',
'Maikop State Technological University',
'Mari State Technical University',
'Mari State University',
'Maritime State University',
'Mendeleev Russian University of Chemical Technology',
'Mendeleev University of Chemical Technology of Russia',
'Michurinsk State Agrarian University',
'Military and Civil Engineering University',
'Military Aviation Engineering University (Voronezh)',
'Military Technical University',
'Military University of Engineering Technology',
'Modern Humanitarian Academy',
'Modern University for the Humanities',
'Mordovia State University',
'Moscow Art - industrial University named after Stroganov',
'Moscow Art Theatre School',
'Moscow City Government University of Management Moscow',
'Moscow City Psychological-Pedagogical University',
'Moscow External University of the Humanities',
'Moscow Pedagogical University',
'Moscow Social Open University',
'Moscow State Agroinginering University',
'Moscow State Aviation Technological University',
'Moscow State Civil Engineering University',
'Moscow State Forestry University',
'Moscow State Geological Prospecting University after named Sergo Ordzhonikidze',
'Moscow State Humanitarian University',
'Moscow State Industrial Art University, named after S.G Stroganov',
'Moscow State Industrial University',
'Moscow State Linguistic University',
'Moscow State Medical Stomatological University (MGMSU)',
'Moscow State Mining University',
'Moscow State Open University',
'Moscow State Pedagogical University',
'Moscow State Regional University',
'Moscow State Technical University',
'Moscow State Technical University of Civil Aviation',
'Moscow State Technological University Stankin',
'Moscow State Technology and Management University',
'Moscow State Textile University A N Kosygin',
'Moscow State Textile University named after A.N Kosygin',
'Moscow State University for Engineering Ecology',
'Moscow State University of Design and Technology',
'Moscow State University of Economics Statistics and Informatics',
'Moscow State University of Environmental Engineering',
'Moscow State University of Food Production',
'Moscow State University of Geodesy and Cartography',
'Moscow State University of Instrument Engineering and Informatics',
'Moscow State University of Precise Mechanics and Computer Science',
'Moscow State University of Printing Arts',
'Moscow State University of Railway Transport',
'Moscow State University of Technology and Management',
'Moscow Technical University of Communications and Informatics',
'Moscow University for the Humanities',
'Moscow University of Industry and Finance',
'Moscow University of Ministry of Internal Affairs of Russian Federation',
'Moscow University of Psychology and Pedagogy',
'Moscow University of Service',
'Moscow University Touro',
'Murmansk State Pedagogical University (MSPU)',
'Murmansk State Technical University',
'National Education Memorial University of Tolstoy Tula',
'National Research University Higher School of Economics',
'Nayanova University',
'Nizhin State M.V.Gogol Pedagogical University',
'Nizhnevartovsk State Pedagogical University',
'Nizhnevartovsk State University for Humanities',
'Nizhny Novgorod State Linguistic University named after N.A Dobrolyubov',
'Nizhny Novgorod State Pedagogical University',
'Nizhny Novgorod State Technical University',
'Nizhny Novgorod State University',
'Nizhny Novgorod State University of Architecture and Civil Engineering',
'North Caucasus State Technical University',
'North Caucasus State Technological University',
'North Ossetian University',
'North West State Technical University',
'North-Caucasian State Technical University',
'North-Eastern State University',
'Northern International University',
'Northern State Medical University',
'Novgorod State University',
'Novosibirsk State Agrarian University',
'Novosibirsk State Medical University',
'Novosibirsk State Pedagogical University',
'Novosibirsk State Technical University',
'Novosibirsk State University',
'Novosibirsk State University of Architecture and Civil Engineering',
'Nyzhny Novgorod State University',
'Obninsk State Technical University for Nuclear Power Engineering',
'Omsk State Agricultural University',
'Omsk State Pedagogical University',
'Omsk State Technical University',
'Omsk State University',
'Omsk State University of Railway Transport',
'Orel State Agrarian University',
'Orel State Technical University',
'Orel State University',
'Orenburg State Agrarian University',
'Orenburg State Pedagogical University',
'Orenburg State University',
'Pacific National University',
'Pacific National University of Economics',
'Pacific State Economic University',
'Pacific State University of Economics',
'Pädagogische Staatsuniversität von Blagowechensk',
'Pedagogical University of Moscow City',
'Penza State Pedagogical University',
'Penza State Pedagogical University Named After VG Belinsky',
'Penza State Technical University',
'Penza State University',
'Penza State University of Architecture and Construction (PSUAC)',
'Peoples’ Friendship University of Russia',
'Pereslavl University',
'Perm State Pedagogical University',
'Perm State Technical University',
'Perm State University',
'Petrozavodsk State University',
'Pomor State University',
'Povolzhsk International Humanities and Technical University',
'Povolzhye State University Service',
'Puscino State University',
'Pushkin Leningrad State University',
'Pyatigorsk State Linguistic University',
'Pyatigorsk State Technological University',
'Rostov State Construction University',
'Rostov State Economic University',
'Rostov State Medical University',
'Rostov State Medical University, Rostov on Don',
'Rostov State Pedagogical University',
'Rostov State University',
'Rostov State University for Railway Transportation',
'Rostovian State Medical University',
'Russian New University (RosNOU)',
'Russian State Humanities University',
'Russian State Hydrometeorological University',
'Russian State Medical University',
'Russian State Open Agrarian University',
'Russian State Open Technical University for Railway Transportation',
'Russian State Open Technical University of Railway Transport',
'Russian State Social University',
'Russian State University for the Humanities',
'Russian State University of Innovative Technologies and Entrepreneurship',
'Russian State University of Physical Culture , Sports and Tourism',
'Russian State University of Tourism and Services',
'Russian State University of Trade and Economics',
'Russian State Vocational and Educational University',
'Russian University of Cooperation - Moscow Consumer Cooperative University',
'Russian University of Innovations',
'Russian-American Christian University (RACU)',
'Russian-German University',
'Ryazan State Pedagogical University',
'Ryazan State Radio Engineering University',
'Ryazan State University',
'Saint Petersburg Christian University',
'Saint Petersburg National Research University of Information Technologies, Mechanics and Optics',
'Saint Petersburg State Agrarian University',
'Saint Petersburg State Electrotechnical University',
'Saint Petersburg State Marine Technical University',
'Saint Petersburg State Pavlov Medical University',
'Saint Petersburg State Polytechnical University',
'Saint Petersburg State Technological University of Plant Polymers',
'Saint Petersburg State University',
'Saint Petersburg State University for Waterways Communications',
'Saint Petersburg State University of Aerospace Instrumentation',
'Saint Petersburg State University of Cinema and Television',
'Saint Petersburg State University of Culture and Arts',
'Saint Petersburg State University of Economics and Finance',
'Saint Petersburg State University of Engineering and Economics',
'Saint Petersburg State University of Physical Training',
'Saint Petersburg State University of Refrigeration and Food Engineering',
'Saint Petersburg State University of Service and Economy',
'Saint Petersburg State University of Technology and Design',
'Saint Petersburg State University of Telecommunication',
'Saint Petersburg State University of Water Communications',
'Saint Petersburg University of GPS of MEM MEASURES of Russia',
'Saint Petersburg University of Humanities and Social Sciences',
'Saint Petersburg University of Ministry of Internal Affairs of Russian Federation',
'Saint Petersburg Water Communications University',
'Saint-Petersburg State University of Architecture and Civil Engineering',
'Sakhalin State University',
'Samara State Aerospace University',
'Samara State Economic University',
'Samara State Medical University',
'Samara State Pedagogical University',
'Samara State Technical University',
'Samara State Transport University',
'Samara State University',
'Samara State University of Architecture and Civil Engineering',
'Saratov State Agrarian University named after N.I.Vavilov',
'Saratov State Medical University',
'Saratov State Socio Economic University',
'Saratov State Socio-Economic University',
'Saratov State Technical University',
'Saratov State Technical University- Inst.of Business Development & Strategy',
'Saratov State University',
'Sergei Witte University of Moscow',
'Shuya State Pedagogical University',
'SHUYA State Pedagogical University (SSPU)',
'Siberian Federal University',
'Siberian State Aerospace University',
'Siberian State Medical University, Federal Agency for Health and Social Development',
'Siberian State Technological University',
'Siberian State Transport University',
'Siberian State University of Physical Culture and Sport',
'Siberian State University of Telecommunications and Informatics',
'Siberian State University Telecommunications and Informatics',
'Siberian University of Consumer Cooperation',
'Siberian University of Consumer Cooperatives',
'Siberian University of Consumer',
'Smolensk Humanities University',
'Smolensk State University',
'Smolny University',
'Sochi State University',
'South - Russian State Technical University Novocherkassk',
'South Federal Pedagogical University',
'South Ossetian State University',
'Southern Federal University',
'Southern Russia State Technical University',
'Southern Russian State University of Economics and Service',
'Southern Ural State University',
'St. Petersburg State Agrarian University',
'St. Petersburg State Marine Technical University',
'St. Petersburg State Polytechnical University',
'St. Petersburg State Technical University',
'St. Petersburg State University of Aerospace Instrumentation',
'St. Petersburg State University of Economics and Finance',
'St. Petersburg State University of Economics and Finance',
'St. Petersburg State University of Refrigeration and Food Technologies',
'St. Petersburg State University of Service and Economy',
'St. Petersburg State University of Transport',
'St. Tikhons Orthodox University',
'St.Petersburg State University of Engineering and Economics',
'Staatsuniversiät von Adygeja',
'State Academic University of Humanitarian Science',
'State Educational Establishment of Higher Professional Education, Udmurt State University',
'State technical University of Altai',
'State University of Amursk, Birobidjan',
'State University of Chechen Republic',
'State University of Land Management',
'State University of Management',
'State Ural University of Transport',
'Stavropol State Agrarian University',
'Stavropol State University',
'Surgut State Pedagogical University',
'Surgut State University',
'Syktyvkar State University',
'T. G. Shevchenko University',
'Tambov State Technical University',
'Tambov State University',
'Tambov State University Named After G.R. Derzhavina',
'Tatar State Humanitarian-Pedagogical University',
'Technologische Staatsuniversität auf den Namen Schuchow W.G. von Belgorod',
'The All-Russia State University of Cinematography of a Name of S.A.Gerasimova',
'The Dagestan State Technical University',
'The Far East State Agrarian University',
'The Ivan Franko State Pedagogical University in Drohobycz',
'The Ivanovo State Architecturally-Building University',
'The Ivanovo State Himiko-Technological University',
'The State Uiversity of the Humanities Sciences',
'The Voronezh State Technical University',
'Togliatti State University',
'Tomsk Polytechnic University',
'Tomsk State Pedagogical University',
'Tomsk State University',
'Tomsk State University of Architecture and Building',
'Tomsk State University of Control Systems and Radioelectronics',
'Transbaikalian State Humanitarian Pedagogical University',
'Tula State Pedagogical University',
'Tula State University',
'Tumen State Oil and Gas University',
'Tuva State University (TSU)',
'Tver State Technical University',
'Tver State Technical University',
'Tver State University',
'Tyva State University',
'Udmurt Republic State University (UdGU)',
'Udmurt State University',
'Ufa State Aviation Technical University',
'Ufa State Petroleum Technological University',
'Ufa State Petroleum Technological University',
'Ukhta State Technical University',
'Uljanowsk State University',
'Ulyanovsk State Pedagogical University Named After I. Ulyanov',
'Ulyanovsk State University',
'University of Commonwealth of Independent States',
'University of Dubna',
'University of Statistics and Information, Belgorog',
'Ural Federal University',
'Ural State Economical University',
'Ural State Forest Engineering University',
'Ural State Mining University, Yekaterinburg',
'Ural State Pedagogical University',
'Ural State Technical University',
'Ural State University',
'Ural State University of Physical Culture (UralGUFK)',
'Vitus Bering Kamchatka State University',
'Vladimir State Humanitarian University',
'Vladimir State University',
'Vladivostock State University of Economics',
'Vladivostok State University of Economics and Service',
'Volga Region State Academy of Physical Culture, Sport and Tourism',
'Volgograd State Pedagogical University',
'Volgograd State Technical University',
'Volgograd State University',
'Volgograd State University of Architecture and Civil Engineering',
'Volgograd State University of Architecture and Civil Engineering (VolgGASU)',
'Vologda State Pedagogical University',
'Vologda State Technical University',
'Voronezh State Agrarian University',
'Voronezh State Pedagogical University',
'Voronezh State Technical University',
'Voronezh State University',
'Voronezh State University of Architecture and Civil Engineering',
'Vyatka State Humanities University',
'Vyatka State Pedagogical University',
'Vyatka State Technical University',
'Vyatka State University',
'World Distributed University (WDU)',
'World Information Distributed University (WIDU)',
'Yakutsky State University',
'Yaroslavl International University of Business and New Technologies',
'Yaroslavl State Pedagogical University',
'Yaroslavl State Technical University',
'Yelets State University of Bunin',
'Yugorsk State University',
]

field_education=[
'Автоматизация и управление',
'Автоматизация технологических процессов и производств',
'Автоматизированное производство химических предприятий',
'Автоматизированное управление жизненным циклом продукции',
'Автоматизированные системы обработки информации и управления',
'Автоматизированные системы управления боевыми авиационными комплексами',
'Автоматизированные технологии и производства',
'Автоматика, телемеханика и связь на железнодорожном транспорте',
'Автоматические системы управления морской техникой',
'Автомобиле- и тракторостроение',
'Автомобили и автомобильное хозяйство',
'Автомобильные дороги и аэродромы',
'Автономные информационные и управляющие системы',
'Агроинженерия',
'Агрономия',
'Агрохимия и агропочвоведение',
'Агроэкология',
'Актерское искусство',
'Акустические приборы и системы',
'Антикризисное управление',
'Антропология',
'Архитектура',
'Астрономия',
'Астрономогеодезия',
'Аудиовизуальная техника',
'Аэронавигационное обслуживание и использование воздушного пространства',
'Аэронавигация',
'Аэрофотогеодезия',
'Баллистика',
'Безопасность жизнедеятельности',
'Безопасность жизнедеятельности в техносфере',
'Безопасность и нераспространение ядерных материалов',
'Безопасность технологических процессов и производств',
'Библиотечно-информационная деятельность',
'Библиотечно-информационные ресурсы',
'Бизнес-информатика',
'Биоинженерия и биоинформатика',
'Биология',
'Биомедицинская инженерия',
'Биомедицинская техника',
'Биотехнические и медицинские аппараты и системы',
'Биотехнология',
'Биофизика',
'Биохимическая физика',
'Биохимия',
'Биоэкология',
'Ботаника',
'Бурение нефтяных и газовых скважин',
'Бухгалтерский учет, анализ и аудит',
'Бытовая радиоэлектронная аппаратура',
'Бытовые машины и приборы',
'Вагоны',
'Вакуумная и компрессорная техника физических установок',
'Ветеринария',
'Ветеринарно-санитарная экспертиза',
'Взрыватели и системы управления средствами поражения',
'Взрывное дело',
'Водные биоресурсы и аквакультура',
'Водные ресурсы и водопользование',
'Водоснабжение и водоотведение',
'Военная безопасность государства',
'Военное и административное управление',
'Военное и государственное управление',
'Военные специальности',
'Востоковедение, африканистика',
'Высоковольтная электроэнергетика и электротехника',
'Высокоэнергетические устройства автоматических систем',
'Вычислительные машины, комплексы, системы и сети',
'Газотурбинные, паротурбинные установки и двигатели',
'Генетика',
'География',
'География и картография',
'Геодезия',
'Геологическая съемка, поиски и разведка месторождений полезных ископаемых',
'Геология',
'Геология и геохимия горючих ископаемых',
'Геология и разведка полезных ископаемых',
'Геология нефти и газа',
'Геофизика',
'Геофизические методы исследования скважин',
'Геофизические методы поисков и разведки месторождений полезных ископаемых',
'Геохимия',
'Геоэкология',
'Гидравлическая, вакуумная и компрессорная техника',
'Гидравлические машины, гидроприводы и гидропневмоавтоматика',
'Гидроаэродинамика',
'Гидроаэродинамика и динамика полета',
'Гидрогеология и инженерная геология',
'Гидрография и навигационное обеспечение судоходства',
'Гидрология',
'Гидрометеорология',
'Гидротехническое строительство',
'Гидроэлектростанции',
'Горное дело',
'Горные машины и оборудование',
'Городское строительство и хозяйство',
'Городской кадастр',
'Государственное и муниципальное управление',
'Графика',
'Гуманитарные и социально-экономические науки',
'Двигатели внутреннего сгорания',
'Двигатели летательных аппаратов',
'Декоративно-прикладное искусство',
'Декоративно-прикладное искусство и народные промыслы',
'Дизайн',
'Дизайн архитектурной среды',
'Динамика и прочность машин',
'Динамика полета и управление движением летательных аппаратов',
'Документоведение и документационное обеспечение управления',
'Домоведение',
'Дошкольная педагогика и психология',
'Драматургия',
'Естественнонаучное образование',
'Живопись',
'Журналистика',
'Защита в чрезвычайных ситуациях',
'Защита окружающей среды',
'Защита растений',
'Защищенные системы связи',
'Звукорежиссура кино и телевидения',
'Звукорежиссура театрализованных представлений и праздников',
'Земельный кадастр',
'Землеустройство',
'Землеустройство и земельный кадастр',
'Зоология',
'Издательское дело и редактирование',
'Изобразительное искусство',
'Изящные искусства',
'Инженерная защита окружающей среды',
'Инженерное дело в медико-биологической практике',
'Инженерные системы сельскохозяйственного водоснабжения, обводнения и водоотведения',
'Иностранный язык',
'Инструментальные системы машиностроительных производств',
'Интегрированные системы летательных аппаратов',
'Интеллектуальные системы в гуманитарной сфере',
'Информатика',
'Информатика и вычислительная техника',
'Информационная безопасность телекоммуникационных систем',
'Информационно-измерительная техника и технологии',
'Информационные системы',
'Информационные системы и технологии',
'Информационные технологии',
'Информационные технологии в дизайне',
'Информационные технологии в медиаиндустрии',
'Информационные технологии в образовании',
'Информационный менеджмент',
'Искусства и гуманитарные науки',
'Искусство балета',
'Искусство интерьера',
'Искусство хореографа',
'Искусствоведение',
'Испытание летательных аппаратов',
'Испытания и эксплуатация авиационной и ракетно-космической техники',
'Исследование природных ресурсов аэрокосмическими средствами',
'Историко-архивоведение',
'История',
'История и теория изобразительного искусства',
'История и теория хореографического искусства',
'Картография',
'Квантовая и оптическая электроника',
'Киноведение',
'Киноискусство',
'Кинооператорство',
'Клиническая психология',
'Книгораспространение',
'Книжное дело',
'Коммерция',
'Комплексная защита объектов информатизации',
'Комплексное использование и охрана водных ресурсов',
'Комплексное обеспечение информационной безопасности автоматизированных систем',
'Композиция',
'Компьютерная безопасность',
'Компьютерные системы управления качеством для автоматизированных производств',
'Конструирование и производство изделий из композиционных материалов',
'Конструирование изделий из кожи',
'Конструирование швейных изделий',
'Конструкторско-технологическое обеспечение машиностроительных производств',
'Конфликтология',
'Корабельное вооружение',
'Корабельные автоматизированные комплексы и информационно-управляющие системы',
'Корабельные системы управления',
'Кораблестроение',
'Кораблестроение и океанотехника',
'Космическая геодезия',
'Космические летательные аппараты и разгонные блоки',
'Котло- и реакторостроение',
'Криптография',
'Культурология',
'Лазерная техника и лазерные технологии',
'Лазерные системы в ракетной технике и космонавтике',
'Лесное дело',
'Лесное хозяйство',
'Лесное хозяйство и ландшафтное строительство',
'Лесоинженерное дело',
'Летная эксплуатация воздушных судов',
'Лечебное дело',
'Лингвистика',
'Лингвистика и межкультурная коммуникация',
'Лингвистика и новые информационные технологии',
'Литейное производство черных и цветных металлов',
'Литературное творчество',
'Логистика',
'Логопедия',
'Локомотивы',
'Маркетинг',
'Маркшейдерское дело',
'Математика',
'Математика. Компьютерные науки',
'Математика. Прикладная математика',
'Математические методы в экономике',
'Математическое обеспечение и администрирование информационных систем',
'Материаловедение в машиностроении',
'Материаловедение и технология новых материалов',
'Материаловедение, технологии материалов и покрытий',
'Машиностроительные технологии и оборудование',
'Машины и аппараты пищевых производств',
'Машины и аппараты текстильной и легкой промышленности',
'Машины и аппараты химических производств',
'Машины и оборудование лесного комплекса',
'Машины и оборудование нефтяных и газовых промыслов',
'Машины и оборудование природообустройства и защиты окружающей среды',
'Машины и технология высокоэффективных процессов обработки материалов',
'Машины и технология литейного производства',
'Машины и технология обработки металлов давлением',
'Медико-профилактическое дело',
'Медицинская биофизика',
'Медицинская биохимия',
'Медицинская кибернетика',
'Медицинская физика',
'Международные отношения',
'Мелиорация, рекультивация и охрана земель',
'Менеджмент',
'Менеджмент высоких технологий',
'Менеджмент организации',
'Металловедение и термическая обработка металлов',
'Металлообрабатывающие станки и комплексы',
'Металлургические машины и оборудование',
'Металлургия',
'Металлургия сварочного производства',
'Металлургия техногенных и вторичных ресурсов',
'Металлургия цветных металлов',
'Металлургия черных металлов',
'Метеорология',
'Метрология и метрологическое обеспечение',
'Метрология, стандартизация и сертификация',
'Механизация и автоматизация строительства',
'Механизация переработки сельскохозяйственной продукции',
'Механизация сельского хозяйства',
'Механика',
'Механика. Прикладная математика',
'Механическое оборудование и технологические комплексы предприятий строительных материалов, изделий и конструкций',
'Мехатроника',
'Мехатроника и робототехника',
'Микробиология',
'Микросистемная техника',
'Микроэлектроника и полупроводниковые приборы',
'Микроэлектроника и твердотельная электроника',
'Мировая экономика',
'Многоканальные телекоммуникационные системы',
'Многоцелевые гусеничные и колесные машины',
'Моделирование и исследование операций в организационно-технических системах',
'Монументально-декоративное искусство',
'Морская акустика и гидрофизика',
'Морские информационные системы и оборудование',
'Морские нефтегазовые сооружения',
'Мосты и транспортные тоннели',
'Музейное дело и охрана памятников',
'Музеология',
'Музыкальная звукорежиссура',
'Музыкальное искусство',
'Музыкальное образование',
'Музыковедение',
'Наземные транспортные системы',
'Налоги и налогообложение',
'Наноматериалы',
'Нанотехнология',
'Нанотехнология в электронике',
'Народная художественная культура',
'Народное художественное творчество',
'Национальная экономика',
'Нетрадиционные и возобновляемые источники энергии',
'Нефтегазовое дело',
'Обогащение полезных ископаемых',
'Оборудование и агрегаты нефтегазового производства',
'Оборудование и технология повышения износостойкости и восстановления деталей машин и аппаратов',
'Оборудование и технология сварочного производства',
'Оборудование нефтегазопереработки',
'Обработка металлов давлением',
'Океанология',
'Океанотехника',
'Олигофренопедагогика',
'Оптико-электронные приборы и системы',
'Оптические технологии и материалы',
'Оптотехника',
'Организационно-технические системы',
'Организация и ведение радиоразведки',
'Организация и технология защиты информации',
'Организация и управление наукоемкими производствами',
'Организация морально-психологического обеспечения',
'Организация перевозок и управление на транспорте',
'Организация правительственной связи',
'Организация работы с молодежью',
'Оружие и системы вооружения',
'Основные процессы химических производств и химическая кибернетика',
'Открытые горные работы',
'Охрана окружающей среды и рациональное использование природных ресурсов',
'Педагогика',
'Педагогика балета',
'Педагогика и методика дошкольного образования',
'Педагогика и методика начального образования',
'Педагогика и психология',
'Педиатрия',
'Перевод и переводоведение',
'Пищевая биотехнология',
'Пищевая инженерия',
'Пищевая инженерия малых предприятий',
'Плазменные энергетические установки',
'Плодоовощеводство и виноградарство',
'Подвижной состав железных дорог',
'Подводная техника',
'Подземная разработка месторождений полезных ископаемых',
'Подъемно-транспортные, строительные, дорожные машины и оборудование',
'Пожарная безопасность',
'Поиски и разведка подземных вод и инженерно-геологические изыскания',
'Полиграфические машины и автоматизированные комплексы',
'Полиграфия',
'Политология',
'Порошковая металлургия, композиционные материалы, покрытия',
'Почвоведение',
'Правоохранительная деятельность',
'Приборостроение',
'Приборы и методы контроля качества и диагностики',
'Приборы и системы лучевой энергетики',
'Приборы и системы ориентации, стабилизации и навигации',
'Прикладная геодезия',
'Прикладная геология',
'Прикладная геохимия, петрология, минералогия',
'Прикладная информатика',
'Прикладная математика',
'Прикладная математика и информатика',
'Прикладная механика',
'Прикладная этика',
'Прикладные математика и физика',
'Природообустройство',
'Природоохранное обустройство территорий',
'Природопользование',
'Прицельно-навигационные системы летательных аппаратов',
'Программное обеспечение вычислительной техники и автоматизированных систем',
'Продюсерство кино и телевидения',
'Проектирование зданий',
'Проектирование и технология радиоэлектронных средств',
'Проектирование и технология электронно-вычислительных средств',
'Проектирование и технология электронных средств',
'Проектирование текстильных изделий',
'Проектирование технических и технологических комплексов',
'Проектирование, сооружение и эксплуатация газонефтепроводов и газонефтехранилищ',
'Производство продуктов питания из растительного сырья',
'Производство строительных материалов, изделий и конструкций',
'Промышленная теплоэнергетика',
'Промышленная электроника',
'Промышленное и гражданское строительство',
'Промышленное рыболовство',
'Противодействие техническим разведкам',
'Психология',
'Радиационная безопасность человека и окружающей среды',
'Радиосвязь, радиовещание и телевидение',
'Радиотехника',
'Радиофизика',
'Радиофизика и электроника',
'Радиоэлектронные системы',
'Разработка и эксплуатация нефтяных и газовых месторождений',
'Ракетные двигатели',
'Рациональное использование материальных и энергетических ресурсов',
'Режиссура кино и телевидения',
'Режиссура мультимедиа-программ',
'Режиссура театра',
'Режиссура театрализованных представлений и праздников',
'Реклама',
'Рекреация и спортивно-оздоровительный туризм',
'Релейная защита и автоматизация электроэнергетических систем',
'Религиоведение',
'Религиоведение',
'Реновация средств материального производства в машиностроении',
'Реставрация',
'Реставрация и реконструкция архитектурного наследия',
'Робототехнические системы авиационного вооружения',
'Роботы и робототехнические системы',
'Родной язык и литература',
'Русский язык и литература',
'Рыболовство',
'Садово-парковое и ландшафтное строительство',
'Самолето- и вертолетостроение',
'Светотехника и источники света',
'Связи с общественностью',
'Селекция и генетика сельскохозяйственных культур',
'Сельскохозяйственные машины и оборудование',
'Сервис',
'Сестринское дело',
'Сети связи и системы коммутации',
'Системный анализ и управление',
'Системотехника объектов морской инфраструктуры',
'Системы автоматизированного проектирования',
'Системы жизнеобеспечения и защиты ракетно-космических аппаратов',
'Системы жизнеобеспечения и оборудования летательных аппаратов',
'Системы обеспечения движения поездов',
'Системы объектов морской инфраструктуры',
'Системы приводов летательных аппаратов',
'Системы управления движением и навигация',
'Системы управления летательными аппаратами',
'Системы электроэнергетики и автоматизации судов',
'Скульптура',
'Социальная антропология',
'Социальная педагогика',
'Социальная работа',
'Социально-культурная деятельность',
'Социально-культурный сервис и туризм',
'Социально-экономическое образование',
'Социология',
'Специальная дошкольная педагогика и психология',
'Специальная психология',
'Специальности в области информационной безопасности',
'Средства аэродромно-технического обеспечения полетов авиации',
'Средства поражения и боеприпасы',
'Средства радиоэлектронной борьбы',
'Средства связи с подвижными объектами',
'Стандартизация и сертификация',
'Стандартизация, сертификация и метрология',
'Стартовые и технические комплексы ракет и космических аппаратов',
'Статистика',
'Стоматология',
'Стрелково-пушечное, артиллерийское и ракетное оружие',
'Строительство',
'Строительство железных дорог, путь и путевое хозяйство',
'Судебная экспертиза',
'Судовое оборудование',
'Судовождение',
'Судовые энергетические установки',
'Сурдопедагогика',
'Сценография',
'Таможенное дело',
'Театральное искусство',
'Театроведение',
'Телекоммуникации',
'Теология',
'Теоретическая и прикладная лингвистика',
'Теория и методика преподавания иностранных языков и культур',
'Теория и практика межкультурной коммуникации',
'Тепловые электрические станции',
'Теплогазоснабжение и вентиляция',
'Теплофизика',
'Теплофизика, автоматизация и экология промышленных печей',
'Теплоэнергетика',
'Техника и физика низких температур',
'Техническая физика',
'Техническая физика термоядерных реакторов и плазменных установок',
'Техническая эксплуатация авиационных электросистем и пилотажно-навигационных комплексов',
'Техническая эксплуатация летательных аппаратов и двигателей',
'Техническая эксплуатация судов и судового оборудования',
'Техническая эксплуатация транспортного радиооборудования',
'Технические науки',
'Технологии геологической разведки',
'Технологические машины и оборудование',
'Технологические машины и оборудование для разработки торфяных месторождений',
'Технологическое образование',
'Технология бродильных производств и виноделие',
'Технология деревообработки',
'Технология детского и функционального питания',
'Технология жиров, эфирных масел и парфюмерно-косметических продуктов',
'Технология и дизайн упаковочного производства',
'Технология и конструирование изделий легкой промышленности',
'Технология и оборудование лесозаготовительных и деревообрабатывающих производств',
'Технология и оборудование производства натуральных волокон',
'Технология и оборудование производства химических волокон и композиционных материалов на их основе',
'Технология и предпринимательство',
'Технология и проектирование текстильных изделий',
'Технология и техника разведки месторождений полезных ископаемых',
'Технология изделий из кожи',
'Технология кинофотоматериалов и магнитных носителей',
'Технология кожи и меха',
'Технология консервов и пищеконцентратов',
'Технология лесозаготовительных и деревоперерабатывающих производств',
'Технология машиностроения',
'Технология молока и молочных продуктов',
'Технология мяса и мясных продуктов',
'Технология обработки драгоценных камней и металлов',
'Технология обслуживания и ремонта машин в агропромышленном комплексе',
'Технология переработки пластических масс и эластомеров',
'Технология пиротехнических средств',
'Технология полиграфического и упаковочного производства',
'Технология полиграфического производства',
'Технология приборостроения',
'Технология продовольственных продуктов специального назначения и общественного питания',
'Технология продуктов общественного питания',
'Технология продуктов питания',
'Технология производства и переработки сельскохозяйственной продукции',
'Технология рыбы и рыбных продуктов',
'Технология сахаристых продуктов',
'Технология средств химической защиты',
'Технология субтропических и пищевкусовых продуктов',
'Технология сырья и продуктов животного происхождения',
'Технология текстильных изделий',
'Технология химической переработки древесины',
'Технология хлеба, кондитерских и макаронных изделий',
'Технология хранения и переработки зерна',
'Технология художественного оформления спектакля',
'Технология художественной обработки материалов',
'Технология швейных изделий',
'Технология электрохимических производств',
'Технология энергонасыщенных материалов и изделий',
'Технология, конструирование изделий и материалы легкой промышленности',
'Технология, оборудование и автоматизация машиностроительных производств',
'Тифлопедагогика',
'Транспортное строительство',
'Транспортные комплексы ракетной техники',
'Транспортные машины и транспортно-технологические комплексы',
'Триботехника',
'Туризм',
'Управление и информатика в технических системах',
'Управление инновациями',
'Управление качеством',
'Управление комплексной автоматизацией процессов управления силами флота',
'Управление персоналом',
'Управление производством и развитием вооружения и военной техники',
'Управление системами связи и автоматизированными системами управления силами флота',
'Управление соединениями железнодорожных войск Российской Федерации',
'Управление финансовым обеспечением Вооруженных сил Российской Федерации',
'Управление штурманской службой Военно-Морского Флота',
'Управляющие, пилотажно-навигационные и электроэнергетические комплексы летательных аппаратов',
'Фармация',
'Физика',
'Физика Земли и планет',
'Физика и техника оптической связи',
'Физика кинетических явлений',
'Физика конденсированного состояния вещества',
'Физика металлов',
'Физика открытых нелинейных систем',
'Физика пучков заряженных частиц и ускорительная техника',
'Физико-математическое образование',
'Физико-химия процессов и материалов',
'Физиология',
'Физическая культура',
'Физическая культура и спорт',
'Физическая электроника',
'Физические процессы горного или нефтегазового производства',
'Физическое материаловедение',
'Филологическое образование',
'Филология',
'Философия',
'Финансы и кредит',
'Фотограмметрия и дистанционное зондирование',
'Фотоника и оптоинформатика',
'Фундаментальная радиофизика и физическая электроника',
'Химическая технология высокомолекулярных соединений',
'Химическая технология высокомолекулярных соединений и полимерных материалов',
'Химическая технология и биотехнология',
'Химическая технология и оборудование отделочного производства',
'Химическая технология материалов современной энергетики',
'Химическая технология монокристаллов, материалов и изделий электронной техники',
'Химическая технология неорганических веществ',
'Химическая технология неорганических веществ и материалов',
'Химическая технология органических веществ',
'Химическая технология органических веществ и топлива',
'Химическая технология органических соединений азота',
'Химическая технология полимерных волокон и текстильных материалов',
'Химическая технология полимерных композиций, порохов и твердых ракетных топлив',
'Химическая технология природных энергоносителей и углеродных материалов',
'Химическая технология редких элементов и материалов на их основе',
'Химическая технология синтетических биологически активных веществ',
'Химическая технология тугоплавких неметаллических и силикатных материалов',
'Химическая технология энергонасыщенных материалов и изделий',
'Химия',
'Химия, физика и механика материалов',
'Холодильная, криогенная техника и кондиционирование',
'Хореографическое исполнительство',
'Художественное образование',
'Художественное проектирование изделий из кожи',
'Художественное проектирование изделий текстильной и легкой промышленности',
'Художественное проектирование костюма',
'Художественное проектирование текстильных изделий',
'Художественное проектирование ювелирных изделий',
'Шахтное и подземное строительство',
'Экологическая геология',
'Экология',
'Экология и природопользование',
'Экономика',
'Экономика труда',
'Экономическая теория',
'Экспертиза и управление недвижимостью',
'Эксплуатация авиационной и космической техники',
'Эксплуатация водного транспорта и транспортного оборудования',
'Эксплуатация воздушных судов и организация воздушного движения',
'Эксплуатация наземного транспорта и транспортного оборудования',
'Эксплуатация перегрузочного оборудования портов и транспортных терминалов',
'Эксплуатация судового электрооборудования и средств автоматики',
'Эксплуатация судовых энергетических установок',
'Эксплуатация транспортных средств',
'Электрификация и автоматизация сельского хозяйства',
'Электрические и электронные аппараты',
'Электрические станции',
'Электрический транспорт',
'Электрический транспорт железных дорог',
'Электроизоляционная, кабельная и конденсаторная техника',
'Электромеханика',
'Электроника и автоматика физических установок',
'Электроника и микроэлектроника',
'Электронное машиностроение',
'Электронные приборы и устройства',
'Электрооборудование автомобилей и тракторов',
'Электрооборудование и автоматика судов',
'Электрооборудование и электрохозяйства предприятий, организаций и учреждений',
'Электрооборудование летательных аппаратов',
'Электропривод и автоматика промышленных установок и технологических комплексов',
'Электроракетные двигатели и энергетические установки',
'Электроснабжение',
'Электроснабжение железных дорог',
'Электротехника, электромеханика и электротехнологии',
'Электротехнологические установки и системы',
'Электроэнергетика',
'Электроэнергетические системы и сети',
'Энергетика теплотехнологий',
'Энерго- и ресурсосберегающие процессы в химической технологии, нефтехимии и биотехнологии',
'Энергомашиностроение',
'Энергообеспечение предприятий',
'Эргономика',
'Этномузыкология',
'Юриспруденция',
'Ядерные реакторы и энергетические установки',
'Ядерные физика и технологии',
] 

company_arr=[
			' ОАО АК Транснефть',
' Группа Компаний Никохим',
' ЗАО фирма Агрокомплекс',
' ОАО Адмиралтейские верфи',
' ОАО ЕвроСибЭнерго вкл. Иркутскэнерго',
' ОАО Завод Красное Сормово',
' ОАО Межрегиональный ТранзитТелеком',
' ООО Группа компаний САХО',
' ФГУП ЦКБ тяжелого машиностроения',
'X5 Retail Group N.V.',
'Агропромышленный холдинг Мираторг',
'Агрохолдинг Продо',
'Акрон',
'АМО ЗИЛ',
'Аптечная сеть 36,6',
'АФК Система',
'Верофарм',
'Группа Амурметалл',
'Группа компаний Ист-лайн',
'Группа компаний Нэфис',
'Группа Магнезит',
'ГУП Калининградский янтарный комбинат',
'ЗАО АВК Эксима',
'ЗАО Алроса',
'ЗАО ГЕОТЭК Холдинг',
'ЗАО Группа ЧТПЗ',
'ЗАО Интеко',
'ЗАО МК Авида',
'ЗАО Моссельпром',
'ЗАО Объединенная металлургическая компания',
'ЗАО Приосколье',
'ЗАО Птицефабрика Роскар',
'ЗАО Седин',
'ЗАО Сибирская аграрная группа',
'ЗАО СУ-155',
'ЗАО Управляющая компания ЭФКО',
'ЗАО Холдинговая компания Золотой Колос',
'Каменск-Уральский металлургический завод',
'Кировградский завод твердых сплавов',
'Компания Вольфрам',
'Красноярский завод цветных металлов имени В. Н. Гулидова',
'Кузбассразрезуголь',
'Куйбышевазот',
'МГТС',
'Металлургический завод Электросталь',
'Минерал Групп',
'Минерально-химическая компания Еврохим',
'Московский электрозавод',
'Мосхимфармпрепараты',
'Моторостроитель',
'Нижнекамскшина',
'Новатэк',
'Новосибирский оловянный комбинат',
'НПО Микроген МЗ РФ',
'НПО Сатурн',
'НПО Сатурн',
'ОАО Авиакомпания Сибирь',
'ОАО Авиакомпания Уральские авиалинии',
'ОАО Авиакомпания ЮТэйр',
'ОАО АвтоВАЗ',
'ОАО АК Трансаэро',
'ОАО Алтайвагонзавод',
'ОАО Амурский судостроительный завод',
'ОАО Ангстрем',
'ОАО АПК ОГО',
'ОАО АПК Стойленская нива',
'ОАО Архангельский ЦБК',
'ОАО Аэропорт Кольцово',
'ОАО Аэропорт Толмачёво',
'ОАО Аэрофлот',
'ОАО Балтийский завод',
'ОАО Башкирэнерго',
'ОАО Башнефть',
'ОАО Вамин Татарстан',
'ОАО Вимм-Билль-Данн Продукты Питания',
'ОАО Востокцемент',
'ОАО Выборгский судостроительный завод',
'ОАО Вымпелком',
'ОАО Газпром',
'ОАО Главстрой',
'ОАО ГМК Норильский никель',
'ОАО Группа Белон',
'ОАО Группа Илим',
'ОАО Группа компаний Виктория',
'ОАО Группа компаний ПИК',
'ОАО Группа компаний Русское море',
'ОАО Группа ЛСР',
'ОАО Группа Разгуляй',
'ОАО Группа Черкизово',
'ОАО Дальневосточная транспортная группа',
'ОАО Дальневосточное морское пароходство',
'ОАО ДВЗ Звезда',
'ОАО Дикси Групп',
'ОАО ДСК-1',
'ОАО Евроцемент групп',
'ОАО Звездочка',
'ОАО Ивановский завод тяжелого станкостроения',
'ОАО Интер РАО ЕЭС',
'ОАО Иркутская сетевая компания',
'ОАО КамАЗ',
'ОАО Кировский завод',
'ОАО Климов',
'ОАО Компания Юнимилк',
'ОАО Комплексные энергетические системы',
'ОАО Кондопога',
'ОАО Концерн Вега',
'ОАО Концерн ПВО Алмаз-Антей',
'ОАО Концерн Созвездие',
'ОАО Корпорация Тактическое ракетное вооружение',
'ОАО Красный Восток Агро',
'ОАО Ленское объединенное речное пароходство',
'ОАО Лента',
'ОАО Ленэнерго',
'ОАО Магнит',
'ОАО МегаФон',
'ОАО Международный аэропорт Внуково',
'ОАО Международный аэропорт Калининград',
'ОАО Международный аэропорт Пулково',
'ОАО Международный аэропорт Сочи',
'ОАО ММП им. В. В. Чернышева',
'ОАО Мордовцемент',
'ОАО Московское речное пароходство',
'ОАО Мотовилихинские заводы',
'ОАО МОЭСК',
'ОАО Мурманское морское пароходство',
'ОАО Нижегородский масложировой комбинат',
'ОАО НК Лукойл',
'ОАО НК Роснефть',
'ОАО Новолипецкий металлургический комбинат',
'ОАО Новороссийский морской торговый порт',
'ОАО Новоросцемент',
'ОАО НПК Уралвагонзавод',
'ОАО ОАК',
'ОАО Объединенные машиностроительные заводы',
'ОАО Обь-Иртышское речное пароходство',
'ОАО ОК Русал',
'ОАО ОСК',
'ОАО Первый канал',
'ОАО Пермский моторный завод',
'ОАО Полиметалл',
'ОАО Приморское морское пароходство',
'ОАО ПСЗ Янтарь',
'ОАО РАО Энергетические системы Востока',
'ОАО Распадская',
'ОАО Российские железные дороги',
'ОАО Росспиртпром',
'ОАО Ростовский порт',
'ОАО Ростсельмаш',
'ОАО Рузаевский завод химического машиностроения',
'ОАО РусГидро',
'ОАО Русснефть',
'ОАО Рязанский станкозавод',
'ОАО Савёловский машиностроительный завод',
'ОАО Светлана',
'ОАО Связьинвест',
'ОАО Себряковцемент',
'ОАО Северная верфь',
'ОАО Северо-западное пароходство',
'ОАО Северсталь — Российская сталь',
'ОАО Севмаш',
'ОАО Седьмой континент',
'ОАО Сибирская Губерния',
'ОАО Сибирский цемент',
'ОАО СИБУР Холдинг',
'ОАО Силовые машины',
'ОАО Ситроникс',
'ОАО Славнефть',
'ОАО Совкомфлот',
'ОАО Соллерс',
'ОАО Средне-Невский судостроительный завод',
'ОАО Судоходная компания Волжское пароходство',
'ОАО Сургутнефтегаз',
'ОАО Татнефть им. В. Д. Шашина',
'ОАО Татэнерго',
'ОАО ТНК-ВР Холдинг',
'ОАО Торговый дом Копейка',
'ОАО Трансмашхолдинг',
'ОАО ТРК Петербург — Пятый канал',
'ОАО Трубная металлургическая компания',
'ОАО Тюменьэнерго',
'ОАО УГМК-Холдинг',
'ОАО УК ММК включая Магнитогорский метизный завод',
'ОАО УМПО',
'ОАО Уралвагонзавод',
'ОАО Уралкалий',
'ОАО Фармстандарт',
'ОАО ФСК ЕЭС',
'ОАО Холдинг МРСК',
'ОАО Целлюлозно-бумажный комбинат Волга',
'ОАО ЭМАльянс',
'ООО Авиакомпания',
'ООО АПК Аркада',
'ООО ГК Агро-Белогорье',
'ООО Группа компаний Доминант',
'ООО Группа компаний Русагро',
'ООО Завод полимеров Кирово-чепецкого химического комбината',
'ООО Зерновая компания Настюша',
'ООО Лесопромышленная компания Континенталь Менеджмент',
'ООО МЭЗ Юг Руси',
'ООО Продимекс-холдинг',
'ООО РАТМ Цемент Холдинг',
'ООО УК Металлоинвест',
'ООО УК Мечел',
'ООО УК Солнечные продукты',
'ООО Управляющая компания Русские фермы',
'Полюс-Золото',
'Приморский ГОК',
'Протек',
'РТРС',
'Русская горнорудная компания',
'Русская медная компания',
'Русский уголь',
'Саянскхимпласт',
'СИА ИНТЕРНЕЙШНЛ ЛТД',
'Сибуглемет',
'Сильвинит',
'СинБио',
'Соликамский магниевый завод',
'Стерлитамакский станкостроительный завод',
'СУЭК',
'Таттелеком',
'Тольяттиазот',
'УК Союзметаллресурс',
'Уралхим',
'Уфанефтехим',
'Фарм-центр',
'Фармсинтез',
'ФГУП ВГТРК',
'ФГУП ИТАР-ТАСС',
'ФГУП Конструкторское бюро Арсенал им. М. И. Фрунзе',
'ФГУП Космическая связь',
'ФГУП Крыловский государственный научный центр',
'ФГУП ММПП Салют',
'ФГУП Научно-производственное предприятие Полёт',
'ФГУП Ордена Трудового Красного Знамени ЦНИИ Комета',
'ФГУП Почта России',
'ФГУП РАМИ РИА Новости',
'ФГУП Росморпорт',
'ФГУП Российский научный центр Прикладная химия',
'ФГУП ТТЦ Останкино',
'Фосагро',
'Химрар',
'ХК Амтел',
'ХК Тракторные заводы',
'Челябинский электрометаллургический комбинат',
'Эвалар',
'Элсиб',
'ЭСТАР',
'Якутскэнерго',
			]

position_arr=[
'Ведущий инженер',
'Ведущий инженер-конструктор',
'Ведущий инженер-проектировщик',
'Ведущий менеджер',
'Ведущий специалист-эксперт',
'Менеджер',
'Менеджер проекта',
'Специалист',
'Старший инженер',
'Старший проект-менеджер',
'Диспетчер',
'Менеджер',
'Менеджер по продажам',
'Seo-оптимизатор',
'Web-дизайнер',
'Администратор',
'Администратор 1С',
'Ведущий специалист-эксперт',
'Инженер',
'Инженер-программист',
'Инженер-программист-разработчик',
'Инженер-электроник',
'Инженер-электронщик',
'Оператор',
'Оператор 1С',
'Оператор БД',
'Оператор ПК',
'Оператор ПК (1С)',
'Помощник системного администратора',
'Программист',
'Программист 1С',
'Разработчик',
'Сервисный инженер',
'Системный администратор',
'Специалист',
'Специалист-эксперт',
'Технолог-программист',
'Курьер',
'Курьер-консультант',
'Курьер-экспедитор',
'Аудитор',
'Бухгалтер',
'Бухгалтер-калькулятор',
'Бухгалтер-кассир',
'Бухгалтер-операционист',
'Бухгалтер-расчетчик',
'Бухгалтер-экономист',
'Ведущий бухгалтер',
'Ведущий специалист-эксперт',
'Ведущий экономист',
'Главный бухгалтер',
'Главный государственный налоговый инспектор',
'Главный экономист',
'Гос. налоговый инспектор',
'Заместитель гл. бухгалтера',
'Кассир-бухгалтер',
'Менеджер',
'Оператор-кассир',
'Помощник бухгалтера',
'Ревизор',
'Специалист',
'Специалист-эксперт',
'Старший бухгалтер',
'Старший государственный налоговый инспектор',
'Старший специалист',
'Финансовый менеджер',
'Экономист',
'Экономист-аналитик',
'Экономист-делопроизводитель',
'Водитель',
]


hh_users=[('geor.zuev682@arterp.ru', 'Hxzn9k'),
('kir.gavril482@arterp.ru', '3Hy1Q4'),
('konaga236@arterp.ru', 'ZWOcXD'),
('anatol.scherba756@arterp.ru', 'E17bXV'),
('nikisaev567@arterp.ru', 'NIQgIh'),
('gennad.logino440@arterp.ru', 'wolkyt'),
('fyokabanov660@arterp.ru', '3a83tz'),
('semytretyak651@arterp.ru', '5645Qa'),
('serge.zaharo148@arterp.ru', 'XRe5CD'),
('oleg.kalin395@arterp.ru', 'w8SPMe'),
('grigor.mishin579@arterp.ru', '7kBmUG'),
('evgeni.mois208@arterp.ru', 'v9JDq5'),
('ivagrigor885@arterp.ru', 'DDYUuq'),
('gennadbyiko919@arterp.ru', 'AuBWTy'),
('vladim.suv501@arterp.ru', 'a8T625'),
('yak.komissa499@arterp.ru', 'IlW2rX'),
('geomois559@arterp.ru', 'UxuIaG'),
('oleg.sor168@arterp.ru', 'norB62'),
('lavrlebede254@arterp.ru', 'XG7dVZ'),
('leonpavl972@arterp.ru', 'kO0hdS'),
('olegkoshe809@arterp.ru', 'JTQS0S'),
('roman.belozerov376@arterp.ru', 'BEamqL'),
('vsevtsv954@arterp.ru', '0RKFAv'),
('viktnos211@arterp.ru', 'fy0xXx'),
('lavrknyaze799@arterp.ru', '9K3pld'),
('filiparhip483@arterp.ru', 'WcXxQq'),
('emmseliver948@arterp.ru', 'YjuyWe'),
('anton.syisoe951@arterp.ru', 'xZdEYU'),
('nikokopyi888@arterp.ru', 'GoC20O'),
('vas.sokolo426@arterp.ru', 'AQtG7A'),
('niko.dorof847@arterp.ru', 'PzYAyc'),
('fyodorfed917@arterp.ru', 'd0ZoTv'),
('vadi.pano898@arterp.ru', 'GFstSX'),
('vasilijtrofimov516@arterp.ru', 'VQ2Ga4'),
('vad.kono655@arterp.ru', '5QQUEn'),
('boris.fila751@arterp.ru', 'LyscUU'),
('anacherno520@arterp.ru', '0cCWhU'),
('georgi.ponoma449@arterp.ru', 'NWOBO5'),
('olemas832@arterp.ru', 'XpGpnn'),
('mihailbiryukov371@arterp.ru', 'O1u9Xm'),
('igo.sok508@arterp.ru', '6YzpeM'),
('filipbobyi385@arterp.ru', 'zXnCvp'),
('egor.turo712@arterp.ru', 'YJFxzm'),
('ant.sorokin378@arterp.ru', 'huZxjK'),
('korn.merk702@arterp.ru', 'fD2hW8'),
('viktorgrigo825@arterp.ru', 'lVMeIT'),
('georgistrel454@arterp.ru', 'yzoctm'),
('aleksaegor121@arterp.ru', 'oVcFlj'),
('yaroslkaban907@arterp.ru', '0Xv3OT'),
('alek.art383@arterp.ru', '1loslH'),
('roman.elise422@arterp.ru', '0leM0y'),
('georgijgrishi239@arterp.ru', 'pB52DL'),
('igor.rom903@arterp.ru', 'vsmtJp'),
('stanisla.molch397@arterp.ru', 'w48Sid'),
('konstantin.kol468@arterp.ru', 'QCtuwI'),
('boribols778@arterp.ru', 'R6F9Oy'),
('ivan.lavrent227@arterp.ru', 'p4zcIk'),
('aleksa.muh231@arterp.ru', 'FLXvc7'),
('danil.bolsha665@arterp.ru', '0qiw4x'),
('nikinos573@arterp.ru', 'MK3hjO'),
('maria.ili879@arterp.ru', 'LiK1mX'),
('anarodiono725@arterp.ru', '2vEUgP'),
('georgi.petuhov766@arterp.ru', 'ioLW6t'),
('vale.miheev490@arterp.ru', 'QBwoTH'),
('bori.artemev637@arterp.ru', 'XLBXkM'),
('kuz.sobol119@arterp.ru', 'KjpXho'),
('oleproho275@arterp.ru', 'jY1jjG'),
('dmisav593@arterp.ru', 'Pe4lKg'),
('pyotr.mas876@arterp.ru', '7PJNFR'),
('leonid.kirillov577@arterp.ru', 'tJivaU'),
('sergejilin349@arterp.ru', '4ep9rF'),
('ernes.sharo656@arterp.ru', 'bnKaHE'),
('igozhukov859@arterp.ru', 'uSt1Uj'),
('valenti.noviko366@arterp.ru', 'BPJMnJ'),
('egor.rodion891@arterp.ru', 'YDyZo7'),
('nikolaj.mir342@arterp.ru', '6OSfwa'),
('alebes168@arterp.ru', 'f02O9U'),
('emman.andre510@arterp.ru', 'fn74Yg'),
('rostgav140@arterp.ru', 'BM7Ocv'),
('vad.petro961@arterp.ru', 'd4Xs6C'),
('mihandree890@arterp.ru', 'HaFdmu'),
('ilykuznetsov899@arterp.ru', 'GfhMw9'),
('ana.shashko820@arterp.ru', 'CWuKpK'),
('geor.soko875@arterp.ru', 'ajv1gf'),
('sergej.nos958@arterp.ru', 'VhfLCq'),
('konstant.myasni693@arterp.ru', 'csc8Wq'),
('vadimvishnyak714@arterp.ru', '4K53iy'),
('teren.syiso751@arterp.ru', '7sVmm4'),
('dmitefimo316@arterp.ru', 'rgcTpU'),
('yur.odints128@arterp.ru', 'mhtKGF'),
('anato.kryil511@arterp.ru', 'wfxhVB'),
('igorkryi829@arterp.ru', 'CY3uSF'),
('evgen.roma293@arterp.ru', '7zJXng'),
('fyodvishny501@arterp.ru', 'XIyHvI'),
('emmanui.nester279@arterp.ru', 'r1tcO4'),
('dani.byi799@arterp.ru', 'qALgDx'),
('vale.komissaro398@arterp.ru', 'waEyml'),
('leonterent880@arterp.ru', 'obovMt'),
('valer.zue265@arterp.ru', '1KjYFD'),
('gennadkolob272@arterp.ru', 'gtmBBc'),
('makar.kudryavt540@arterp.ru', '78k2ce'),
('evgeignat482@arterp.ru', 'BQPyNn'),
('ippolit.dmitr730@arterp.ru', 'oLLZdv'),
('artsidoro121@arterp.ru', 'PHuoYb'),
('romatitov825@arterp.ru', 'beEFmB'),
('igormaks636@arterp.ru', 'hJJ0O4'),
('anatolijkapusti547@arterp.ru', 'FaN56z'),
('marfilat661@arterp.ru', 'EFvv1R'),
('iva.suhano809@arterp.ru', 'vbYJXP'),
('daniimak799@arterp.ru', 's91PwX'),
('artrogov524@arterp.ru', 'GaZXq7'),
('serg.moiseev999@arterp.ru', '9cXP6e'),
('konsta.muhin317@arterp.ru', 'Nq2jVf'),
('ruslan.shu820@arterp.ru', 'W7uk8Q'),
('vitalpah348@arterp.ru', 'NxG2TF'),
('georgger729@arterp.ru', 'BzOKqC'),
('vital.mih696@arterp.ru', '9LS6jw'),
('stepa.kond258@arterp.ru', 'C2cS5t'),
('yar.martyinov243@arterp.ru', 'hhyhIh'),
('gletihon786@arterp.ru', 'n7yRkR'),
('denisgusev694@arterp.ru', '2n4fj3'),
('valenti.konono661@arterp.ru', 'DusMAg'),
('stan.afa239@arterp.ru', 'Uo9DvF'),
('stepadenis646@arterp.ru', 'vnF889'),
('anatolijrya275@arterp.ru', 'xjs6h2'),
('fyo.koshele399@arterp.ru', 'gF6AJu'),
('vitaden562@arterp.ru', '099IOH'),
('leonidmoroz205@arterp.ru', 's21yKi'),
('evg.turo644@arterp.ru', 'xxHY31'),
('afanchernov877@arterp.ru', 'H5qXXx'),
('olevoront152@arterp.ru', 'nDvcwC'),
('filisako376@arterp.ru', 'EKsL8R'),
('valentpol467@arterp.ru', 'ndLsAM'),
('leonid.timofeev452@arterp.ru', 'SNDmaQ'),
('viktor.trety913@arterp.ru', 'yTu5Nx'),
('geor.zuev367@arterp.ru', '0WSeEW'),
('pavestepanov223@arterp.ru', 'zrfju4'),
('valdor400@arterp.ru', 'M9woz1'),
('ivan.zajtsev425@arterp.ru', '5H7o1X'),
('vas.oreh847@arterp.ru', 'mIQVAf'),
('kirdenis763@arterp.ru', 'PpaqHo'),
('valerisobolev657@arterp.ru', 'NpLewq'),
('val.suvorov348@arterp.ru', '47DK77'),
('evgenij.abramo782@arterp.ru', 'UZh63J'),
('viktkryi235@arterp.ru', 'pOiZUx'),
('mirmerkush642@arterp.ru', '4FM7tt'),
('kornejersho499@arterp.ru', '4fSaOI'),
('mihailguschin432@arterp.ru', 'oXuAFD'),
('vladimirbogdan841@arterp.ru', 'doHAwH'),
('vitaersho131@arterp.ru', 'lm43tN'),
('evg.dmi387@arterp.ru', 'LkDpFq'),
('anatopavlo461@arterp.ru', 'DwkdCH'),
('fyodorschu115@arterp.ru', 'yp0RWQ'),
('vitalfok619@arterp.ru', 'BlrSRY'),
('egorodin745@arterp.ru', '9yJOFH'),
('egorodin745@arterp.ru', '9yJOFH'),
('korn.medv535@arterp.ru', 'p1Xwzg'),
('ale.nik573@arterp.ru', 'vbXiz7'),
('kirill.kazakov514@arterp.ru', 'lDp3pP'),
('vadtretya613@arterp.ru', 'OrmCme'),
('korn.medv535@arterp.ru', 'p1Xwzg'),
('bori.kornil268@arterp.ru', 'C7pqVY'),
('leongolube502@arterp.ru', 'aFx4MK'),
('geor.filipp690@arterp.ru', 'TuASnW'),
('yaroslav.odintsov309@arterp.ru', 'Cj5yzG')]



sity_full=['Москва',
'Санкт-Петербург',
'Новосибирск',
'Екатеринбург',
'Нижний Новгород',
'Казань',
'Самара',
'Омск',
'Челябинск',
'Ростов-на-Дону',
'Уфа',
'Волгоград',
'Красноярск',
'Пермь',
'Воронеж',
'Саратов',
'Краснодар',
'Тольятти',
'Тюмень',
'Ижевск',
'Барнаул',
'Ульяновск',
'Иркутск',
'Владивосток',
'Ярославль',
'Хабаровск',
'Оренбург',
'Новокузнецк',
'Томск',
'Кемерово',
'Рязань',
'Астрахань',
'Пенза',
'Набережные Челны',
'Липецк',
'Тула',
'Киров',
'Чебоксары',
'Калининград',
'Курск',
'Улан-Удэ',
'Ставрополь',
'Магнитогорск',
'Брянск',
'Иваново',
'Тверь',
'Белгород',
'Сочи',
'Нижний Тагил',
'Архангельск',
'Владимир',
'Калуга',
'Чита',
'Смоленск',
'Волжский',
'Курган',
'Сургут',
'Орёл',
'Череповец',
'Владикавказ',
'Вологда',
'Мурманск',
'Саранск',
'Якутск',
'Тамбов',
'Грозный',
'Стерлитамак',
'Кострома',
'Петрозаводск',
'Нижневартовск',
'Комсомольск-на-Амуре',
'Йошкар-Ола',
'Таганрог',
'Новороссийск',
'Братск',
'Сыктывкар',
'Нальчик',
'Дзержинск',
'Шахты',
'Орск',
'Нижнекамск',
'Балашиха',
'Ангарск',
'Химки',
'Старый Оскол',
'Великий Новгород',
'Благовещенск',
'Энгельс',
'Подольск',
'Псков',
'Бийск',
'Прокопьевск',
'Рыбинск',
'Балаково',
'Армавир',
'Южно-Сахалинск',
'Северодвинск',
'Королёв',
'Петропавловск-Камчатский',
'Люберцы',
'Мытищи',
'Норильск',
'Сызрань',
'Новочеркасск',
'Златоуст',
'Каменск-Уральский',
'Волгодонск',
'Абакан',
'Находка',
'Уссурийск',
'Электросталь',
'Салават',
'Березники',
'Миасс',
'Альметьевск',
'Рубцовск',
'Пятигорск',
'Коломна',
'Майкоп',
'Ковров',
'Железнодорожный',
'Копейск',
'Одинцово',
'Хасавюрт',
'Кисловодск',
'Новомосковск',
'Красногорск',
'Серпухов',
'Черкесск',
'Нефтеюганск',
'Первоуральск',
'Новочебоксарск',
'Нефтекамск',
'Орехово-Зуево',
'Димитровград',
'Дербент',
'Невинномысск',
'Камышин',
'Новый Уренгой',
'Батайск',
'Кызыл',
'Щёлково',
'Муром',
'Октябрьский',
'Новошахтинск',
'Северск',
'Ачинск',
'Сергиев Посад',
'Ноябрьск',
'Елец',
'Новокуйбышевск',
'Жуковский',
'Обнинск',
'Арзамас',
'Пушкино',
'Домодедово',
'Элиста',
'Каспийск',
'Назрань',
'Артём',
'Ессентуки',
'Ногинск',
'Раменское',
'Бердск',
'Сарапул']

citation=['Если хочешь узнать, что думает о тебе твой знакомый, разозли его.', 
'Трудно говорить правду, если не знаешь, чего от тебя ждут.', 
'Я думаю, мы должны говорить правду или хотя бы говорить то, что мы думаем.', 
'Сказать человеку в глаза всю правду порою больше, чем долг, — это удовольствие.', 
'Правду в глаза лучше всего говорить на ухо.', 
'Если человек вдруг станет говорить все, что он думает, ему не поверят. И будут правы. Что это за человек, который говорит все, что думает.', 
'Не стоит обижаться на правду. Лучше ответить тем же.', 
'Искусство — природа человека', 
'Искусство — диалог, в котором собеседник молчит.', 
'Я знаю, что искусство совершенно необходимо, только не знаю зачем.', 
'Искусство любят те, кому не удалась жизнь.', 
'Искусство начинается там, где начинается чуть-чуть.', 
'Господь Бог живет в деталях.', 
'Искусство — это умение скрыть искусство.', 
'Искусство — это всегда ограничение. Смысл всякой картины в ее рамке.', 
'Искусство не изображает видимое, но делает его видимым.', 
'Искусство не могло бы жить даже без того человека, который мог бы обойтись без искусства.', 
'Только искусство позволяет нам сказать даже то, чего мы не знаем.', 
'Наука успокаивает, искусство же существует для того, чтобы не дать успокоиться.', 
'В искусстве форма все, материал ничего не стоит. Штауб берет за фрак, сшитый из собственного сукна, столько же, сколько за фрак, сшитый из сукна заказчика. Он говорит, что требует плату за фасон, материю же дарит.', 
'Жизнь подражает Искусству в гораздо большей степени, чем Искусство подражает Жизни.', 
'Лондонские туманы не существовали, пока их не открыло искусство.', 
'Жить за счет искусства для искусства — вот истинное искусство.', 
'Если это покупают, значит, это искусство.', 
'Если кто-либо назвал что-либо искусством — это искусство.', 
'Искусство должно быть холодным.', 
'Художественное течение побеждает только тогда, когда его берут на вооружение декораторы витрин.', 
'Для искусства опасны не поджигатели, а пожарные.', 
'На самом деле искусство отражает не жизнь, а зрителя.', 
'Художника можно определить как невротика, который непрерывно лечится искусством.', 
'Творчество — это загадка, которую художник задает сам себе.', 
'Сначала думать, потом говорить — девиз критики', 
'Мало кто создает что-либо творческое после 35-летнего возраста. Причина этого в том, что мало кто создает что-либо творческое до 35-летнего возраста.', 
'Художник должен присутствовать в своем произведении, как Бог во вселенной: быть вездесущим и невидимым.', 
'Есть произведения, которые создаются своей аудиторией.', 
'Мастерство — это когда что и как приходят одновременно.', 
'Только прирожденный художник способен трудиться так, чтобы им стать.', 
'Каждый ребенок — художник. Трудность в том, чтобы остаться художником, выйдя из детского возраста.', 
'Великий художник — это мертвый художник.', 
'Все имеют право меняться, даже художники.', 
'Только ведущий аукциона может беспристрастно и одинаково восхищаться всеми школами искусства.', 
'Карьера художника подобна карьере куртизанки: сначала для собственного удовольствия, потом для чужого, и наконец ради денег.', 
'Такова уж природа искусства: художник не может страдать в одиночку.', 
'Артист должен знать все о любви и научиться жить без нее.', 
'Художник — лжец, но искусство — правда.', 
'Художник — не особая разновидность человека, но каждый человек — особая разновидность художника.']



product_arr=[
		'Выезд специалиста на объект.',
		'Консультация. Экспертное заключение.',
		'Геодезическая съемка 1:100',
		'Геодезическая съемка 1:200',
		'Съемка (М1:200, М1:100) лесных насаждений'
		'Проект благоустройства и озеленения',
		'Схема иллюминации',
		'Проект детальной организации рельефа',
		'Картограмма перемещения',
		'Авторский надзор за реализацией проектных решений',
		'Общий ремонт',
		'Дополнительный ремонт'
		'Монтаж объекта',
		'Демонтаж объекта',
		]


avatar_url_arr=[
'http://png-3.findicons.com/files/icons/376/the_blacy/128/victory.png',
'http://png-1.findicons.com/files/icons/376/the_blacy/128/grimace.png',
'http://png-3.findicons.com/files/icons/1024/dress_it_profession/128/engineer_avatar.png',
'http://png-2.findicons.com/files/icons/178/popo_emotions/128/big_smile.png',
'http://png-3.findicons.com/files/icons/1024/dress_it_profession/128/soldier_avatar.png',
'http://png-5.findicons.com/files/icons/1024/dress_it_profession/128/designer_avatar.png',
'http://png-2.findicons.com/files/icons/1024/dress_it_profession/128/assassin_avatar.png',
'http://png-3.findicons.com/files/icons/178/popo_emotions/128/sad.png',
'http://png-5.findicons.com/files/icons/1024/dress_it_profession/128/fireman_avatar.png',
'http://png-1.findicons.com/files/icons/1024/dress_it_profession/128/nurse_avatar.png',
'http://png-1.findicons.com/files/icons/376/the_blacy/128/super_man.png',
'http://png-4.findicons.com/files/icons/1024/dress_it_profession/128/dad_avatar.png',
'http://png-5.findicons.com/files/icons/178/popo_emotions/128/what.png',
'http://png-5.findicons.com/files/icons/376/the_blacy/128/haha.png',
'http://png-3.findicons.com/files/icons/178/popo_emotions/128/doubt.png',
'http://png-5.findicons.com/files/icons/376/the_blacy/128/money.png',
]